/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */

//one more letter？ 不是多了一个字母的意思？ 而且letter没有复数说明也是多了一个字母。。。
public class LeetCode389 {
    static class Solution {
        public static char findTheDifference(String s, String t) {
            StringBuffer stringBuffer = new StringBuffer();
            stringBuffer.append(t);
            for (int i = 0; i < t.length(); i++) {
                stringBuffer.deleteCharAt(i);
                if (stringBuffer.toString().equals(s))
                    return t.charAt(i);
                else
            stringBuffer.insert(i,t.charAt(i));
            }
            return '.';
        }
    }

    public static void main(String[] args) {
        System.out.println(Solution.findTheDifference("abcd", "wabcd"));
    }
}

